### ISSUE TITLE
Comment header for admin posts doesn't show name

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/site#31]
I've noticed that the name when someone who is logged in makes a comment is now "Anonymous ## Mod". While this is highly amusing, it would be highly useful if it really did put the actual name of the person posting. Having to sign your posts if you are telling people to contact you on IRC would be rather irritating.

**Comment by ameliaikeda** [comment]
Eh, low priority. It requires eager loading otherwise you run into the n + 1 query problem because Laravel models do not use joins (they will do two queries, one to get a list of user ids to fetch, then another to fetch those users in one go). `user_id`s are still stored.

```
select * from `radio_comments` where `news_id` = :id
select * from `users` where `id` in (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
```

It will then turn everything into an instance of `Illuminate\Support\Collection` which you can iterate through like an array.

**Comment by ameliaikeda** [comment]
I love how I say low priority and then fix it instantly.
